name: Build, test and deploy

on: [push, pull_request, workflow_dispatch]

env:
  PYTHONWARNINGS: all

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # , windows-latest]  # Windows passes even when pytests fail
        python: [3.8, 3.9, "3.10", 3.11]  # , 3.12]  # Matplotlib is not yet Py3.12 compatible

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('DEPENDS.txt') }}-${{ hashFiles('DEPENDS-tests.txt') }}-${{ hashFiles('DEPENDS-docs.txt') }}
          restore-keys: ${{ runner.os }}-pip-${{ hashFiles('DEPENDS.txt') }}-

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r DEPENDS.txt -r DEPENDS-tests.txt -r DEPENDS-docs.txt

      - name: Build package
        run: |
          tools/header.py "Dependency versions"
          tools/build_versions.py
          # python setup.py build_ext --inplace
          pip install --editable .

      - name: Run tests
        run: |
          pytest
          # pytest --doctest-modules  # TODO: Fix four failing doctests
          ruff -- --format=github .
      - name: Build docs
        if: matrix.os == 'ubuntu-latest'
        run: |
          make -C docs/ html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: |
          github.repository == 'scikit-fuzzy/scikit-fuzzy' &&
          github.ref == 'ref/head/master' &&
          matrix.os == 'ubuntu-latest' &&
          matrix.python == 3.9
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          external_repository: 'scikit-fuzzy/scikit-fuzzy.github.io'
          publish_branch: 'main'
          publish_dir: 'docs/build/html'
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
